# Generated by Django 4.0.5 on 2022-06-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('size', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
