# Generated by Django 4.0.5 on 2022-06-04 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_stickers_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickers',
            name='username',
        ),
        migrations.AddField(
            model_name='stickers',
            name='user',
            field=models.ForeignKey(blank=True, default=-3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
