# Generated by Django 4.0.5 on 2022-06-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_stickers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickers',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\fsanv\\my_projects\\stickers--site\\stickers_site\\static/media'),
        ),
    ]
