# Generated by Django 4.0.5 on 2022-06-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_stickers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickers',
            name='image',
            field=models.ImageField(upload_to='stickers_images'),
        ),
    ]
