# Generated by Django 4.0.5 on 2022-06-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_stickers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickers',
            name='size',
        ),
        migrations.AlterField(
            model_name='stickers',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
