# Generated by Django 4.0.5 on 2022-06-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_stickers_size_alter_stickers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickers',
            name='size',
            field=models.CharField(default=24, max_length=30),
            preserve_default=False,
        ),
    ]
