# Generated by Django 4.0.5 on 2022-06-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_stickers_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickers',
            name='size',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
